teleop_twist_joy_node:
  ros__parameters:
    # กำหนดแกน Analog
    axis_linear:
      x: 1            # แกน 1 คือ Left Stick (ขึ้น/ลง) สำหรับเดินหน้า-ถอยหลัง
    axis_angular:
      yaw: 2          # แกน 0 คือ Left Stick (ซ้าย/ขวา) สำหรับการเลี้ยว

    # กำหนดความเร็ว (Scale)
    scale_linear:
      x: 0.7          # ความเร็วเดินหน้าสูงสุด (หน่วยเป็นเมตรต่อวินาที: m/s)
    scale_angular:
      yaw: 1.2        # ความเร็วการหมุนสูงสุด (หน่วยเป็น Radian/s)

    # ระบบความปลอดภัย (Safety)
    enable_button: 4  # ต้องกดปุ่ม LB (Left Bumper) ค้างไว้ถึงจะส่งคำสั่งได้

    # โหมดความเร็วสูง (Turbo)
    enable_turbo_button: 5 # กดปุ่ม RB (Right Bumper) ค้างไว้เพื่อวิ่งเร็วขึ้น
    scale_linear_turbo:
      x: 1.5          # ความเร็วสูงสุดในโหมด Turbo
