slam_toolbox:
  ros__parameters:
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan
    use_scan_matching: true
    max_laser_range: 20.0
    resolution: 0.05
    minimum_time_interval: 0.2
    transform_publish_period: 0.05
    map_update_interval: 1.0
    ceres_scan_matcher:
      use_nonmonotonic_steps: false
      max_num_iterations: 20
      num_threads: 1
      ceres_solver_options:
        use_nonmonotonic_steps: false
        max_num_iterations: 20
        num_threads: 1
